"""
황금알을 낳는 거위: 환생 - 모든 밸런스 및 설정 상수
"""

# 화면 및 맵 구성
SCREEN_WIDTH = 960
SCREEN_HEIGHT = 640
TILE_SIZE = 32

# 난이도 모드
DIFFICULTY_EASY = "easy"
DIFFICULTY_NORMAL = "normal"
DIFFICULTY_HARD = "hard"

# 난이도별 배고픔 배율
EASY_HUNGER_MULT = 0.7
NORMAL_HUNGER_MULT = 1.0
HARD_HUNGER_MULT = 1.3

# 미로 크기
MAZE_WIDTH_NORMAL = 25
MAZE_HEIGHT_NORMAL = 17
TUTORIAL_MAZE_WIDTH = 10
TUTORIAL_MAZE_HEIGHT = 10

# 배고픔 수치
BASE_MAX_HUNGER = 100
BASE_HUNGER_RATE = 3.0  # 초당 감소량

# 이동 속도 및 시야
BASE_SPEED = 150  # 픽셀/초
BASE_VISION_RADIUS = 4  # 타일 단위

# 욕심 디버프 임계값
EGG_SPEED_THRESHOLD1 = 10  # 첫 번째 속도 감소 임계값
EGG_SPEED_THRESHOLD2 = 20  # 두 번째 속도 감소 임계값
EGG_VISION_THRESHOLD = 15  # 시야 감소 임계값

# 욕심 디버프 감소율 (퍼센트)
EGG_SPEED_REDUCTION1 = 0.1  # 10% 감소
EGG_SPEED_REDUCTION2 = 0.2  # 20% 감소
EGG_VISION_REDUCTION = 0.2  # 20% 감소

# 오브젝트 배치 밀도
ITEM_DENSITY = 0.05  # 타일당 아이템 확률
MERCHANT_DENSITY = 0.01  # 타일당 상인 확률
SECRET_ROOM_CHANCE = 0.12  # 비밀 방 생성 확률

# 상점/룰렛 파라미터
ROULETTE_EGG_COST = 3
SAFE_TRADE_EGG_COST = 1
ROULETTE_SPIN_TIME = 2.5  # 초
ROULETTE_SLOTS_MIN = 8  # 최소 룰렛 칸 수

# 룰렛 weight 조정 계수
ROULETTE_WEIGHT_DECAY_RATE = 0.1  # 거래 횟수당 좋은 효과 weight 감소율
ROULETTE_WEIGHT_INCREASE_RATE = 0.1  # 거래 횟수당 나쁜 효과 weight 증가율
ROULETTE_WEIGHT_MIN = 0.5  # 좋은 효과 weight 최소값

# 안전 거래 확률
SAFE_TRADE_FOOD_CHANCE = 0.4
SAFE_TRADE_HUNGER_RATE_DOWN_CHANCE = 0.3
SAFE_TRADE_SPEED_UP_CHANCE = 0.2
SAFE_TRADE_HUNGER_INSTANT_UP_CHANCE = 0.1

# 점수 계산
SCORE_EGG_VALUE = 10
SCORE_TIME_BONUS = 1  # 초당 보너스
SCORE_SECRET_ROOM_BONUS = 50

# 랭크 임계값
RANK_S_THRESHOLD = 300
RANK_A_THRESHOLD = 220
RANK_B_THRESHOLD = 150

# 도전 모드 ID
CHALLENGE_NO_GREED = "no_greed"  # 무욕의 길
CHALLENGE_GREED_OVERDRIVE = "greed_overdrive"  # 대부호의 야망
CHALLENGE_GAMBLER_CURSE = "gambler_curse"  # 도박 중독

# 도전 모드 파라미터
CHALLENGE_GREED_OVERDRIVE_TIME_LIMIT = 420  # 7분 (초)
CHALLENGE_GREED_OVERDRIVE_TARGET_EGGS = 20
CHALLENGE_GAMBLER_CURSE_MIN_TRADES = 5

# 상점 상태
SHOP_STATE_NORMAL = "normal"
SHOP_STATE_MENU = "menu"
SHOP_STATE_ROULETTE_SPIN = "roulette_spin"
SHOP_STATE_ROULETTE_RESULT = "roulette_result"

# 아이템 회복량
FOOD_HEAL_MIN = 20
FOOD_HEAL_MAX = 30
FOOD_BOOST_MULTIPLIER = 1.5  # FoodBoost 효과 시 추가 회복 배율

# 효과 지속 시간 (초, -1은 영구)
EFFECT_SPEED_UP_DURATION = 30.0
EFFECT_SPEED_DOWN_DURATION = 20.0
EFFECT_VISION_UP_DURATION = 30.0
EFFECT_VISION_DOWN_DURATION = 20.0
EFFECT_HUNGER_RATE_DOWN_DURATION = 60.0
EFFECT_FOOD_BOOST_DURATION = 120.0
EFFECT_DOUBLE_REWARD_DURATION = 60.0

# 효과 값
EFFECT_SPEED_UP_VALUE = 0.2  # 20% 증가
EFFECT_SPEED_DOWN_VALUE = 0.15  # 15% 감소
EFFECT_VISION_UP_VALUE = 2  # 타일 증가
EFFECT_VISION_DOWN_VALUE = 1  # 타일 감소
EFFECT_HUNGER_RATE_DOWN_VALUE = 0.5  # 50% 감소
EFFECT_HUNGER_INSTANT_UP_VALUE = 15  # 즉시 회복량

# 배고픔 사망 연출
DEATH_FADE_TIME = 1.0  # 초
DEATH_TEXT_DISPLAY_TIME = 1.0  # 초

# 배고픔 경고 임계값
HUNGER_WARNING_THRESHOLD = 0.8  # 80%

# 카메라 설정
CAMERA_FOLLOW_SPEED = 5.0  # 카메라 추적 속도

# 디버그
DEBUG_SHOW_FPS = False
DEBUG_SHOW_GRID = False

